### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by toledox82** [TwistedInteractive/importcsv#10]
The error:

`Fatal error: Maximum execution time of 30 seconds exceeded in /Users/marciotoledo/Work/_WWW/interface.eng.br/extensions/importcsv/lib/parsecsv-0.3.2/parsecsv.lib.php on line 374`

How I change this limit for much more? My csv file have 11,5MB, it's around 1200 articles.

Thanks.

**Comment by kanduvisla** [comment]
This is most probably something you have to change on your server since it's a PHP settings error. You could try `ini_set()` or adding a rule to your `.htaccess`-file for this.
