### ISSUE TITLE
Sub menu 'Import / Export CSV' not shown in 'System' menu in other languages

### ISSUE THREAD

**Issue by xfrenette** [TwistedInteractive/importcsv#11]
I have Symphony 2.3.1 and also the [french translation](https://github.com/bpierre/lang_french). My Symphony is setup to use french.

Once your extension installed, I don't see the sub menu "Import / Export CSV" in the "System" menu.

But if, in [this file](https://github.com/kanduvisla/importcsv/blob/master/extension.driver.php#L26), I change line 26 to:
`'location'   => _('System'),`
it works.

It also creates the same problem with the [Italian language](https://github.com/symphonycms-it/lang_italian), but I didn't test other translations.

How to reproduce:
- Install [french language extension](https://github.com/bpierre/lang_french) 
- Enable french in Preferences
- Install 'Import / Export CSV'
- Problem: the menu is not added to 'System'

**Comment by kanduvisla** [comment]
Could you send a pull request for this?

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
