### ISSUE TITLE
Importing into Members section password issue

### ISSUE THREAD

**Issue by andrewminton** [TwistedInteractive/importcsv#17]
I've successfully imported around 600 entries into a section but am having issues pre-populating the 'member:password' from a generated set of passwords in the CSV.

Upon importing the Data, I've checked the fields and the Password field is set to "weak(1)" rather then the UUID set in the CSV field for password.

Is there anything I'm doing wrong or does the driver for member_password need updating somehow?

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
