### ISSUE TITLE
Import fails completely

### ISSUE THREAD

**Issue by designermonkey** [TwistedInteractive/importcsv#2]
Geil, I have just tried this extension since the last upgrade, and I get the following errors (see attached image on forum thread) for every single batch and therefore every entry.

The extension tells me that all entries are imported, but none are.

**Comment by kanduvisla** [comment]
I'll see if I can look into it. We use symphony on a commercial base, so most of the time our extensions only get updated when a client requieres additional functionality or when we encounter an issue.

Groeten,

Giel
