### ISSUE TITLE
Working with date time extension

### ISSUE THREAD

**Issue by andrewminton** [TwistedInteractive/importcsv#23]
Is there a need to build a driver to export values from the date/time field?

I assumed it would be the same as a normal date field but I get no values on export.

**Comment by andrewminton** [comment]
Are the drivers registered anywhere in the extension? i.e. is there a specific order in which they are loaded?

If I create my own driver it complains about needing the ImportDriver_default class which it can't find.. do I need to include this at the top of the driver file?

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
