### ISSUE TITLE
Symphony 2.4

### ISSUE THREAD

**Issue by wdebusschere** [TwistedInteractive/importcsv#25]
Brendon,

I have donwloaded your contributions, would be great to have multilanguage functionality, 
1. but for the multi language tab the select options for the sections are empty.
2. for the normal import i get in my main.log: 07/08/2014 6:19 pm > UNKNOWN: DatabaseException 0 - MySQL Error (1146): Table 'eccolaluna.sym_entries_data_' doesn't exist in query: SELECT SQL_CACHE \* FROM `sym_entries_data_`; on line 867 of /Users/xxx/Sites/site/symphony/lib/toolkit/class.mysql.php

**Comment by DaveRev** [comment]
Hi! Did you solve this issue?

**Comment by wdebusschere** [comment]
No.. Multi language is not working.

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
