### ISSUE TITLE
Support `prepareImportValue` function?

### ISSUE THREAD

**Issue by brendo** [TwistedInteractive/importcsv#4]
If you aren't already aware, the XMLImporter extension does a similar thing to the Import CSV extension in that it needs to take a single value and allow fields to process it so that it can be correctly saved.

While I love the idea of drivers for each field, it places a little of the responsibility on the you to maintain the pull requests for each field and it can be unmanageable. 

To prevent this, the XMLImporter looks for a `prepareImportValue` on the Field class, which is given a string and returns an array ready for insertion. 

Perhaps it'd be nice if Import CSV extension also checked to see if the Field has implemented this function before falling back to use the default driver?

So the pecking order would then be:
1. Field's `prepareImportValue` function
2. Specific Field Driver
3. Default Field Driver

What do you think?

**Comment by kanduvisla** [comment]
Could you provide some examples of fields with this `prepareImportValue`-function? Or do you mean the `prepareTableValue`-function?

**Comment by brendo** [comment]
No, it's `prepareImportValue`, here's a couple of extensions that implement it:
- [DateTime](https://github.com/hananils/datetime/blob/master/fields/field.datetime.php#L283-313)
- [Subsection Manager](https://github.com/hananils/subsectionmanager/blob/master/fields/field.subsectionmanager.php#L791-804)
- [Meta Keys](https://github.com/brendo/field_metakeys/blob/master/fields/field.metakeys.php#L252-281)

There is also a Symphony function, `Field->canImport()` that is currently marked as deprecated. It would however seem to be useful, so I'm rethinking my decision to remove it and instead may add `prepareImportValue` into the core Field class for 2.3 so there a bit of a standard for how Fields can import their data :)

**Comment by brendo** [comment]
I want to pick this up again, I've already written a driver that works with the [dev DateTime](https://github.com/hananils/datetime/commit/6816525be1094a0ccabdcb2c78e3c150a449d0d6) and it's quite [a simple implementation](https://gist.github.com/brendo/5408899) :D

At the moment I think we will need to check to see if a field supports the `prepareImportValue` or `prepareExportValue` and if so, use that, otherwise use your existing work.

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
