### ISSUE TITLE
Error accessing the content.index.php backend page

### ISSUE THREAD

**Issue by andrewminton** [TwistedInteractive/importcsv#5]
I keep getting this error when I try to access the content.index.php page on a 2.2.5 install?

Fatal error: Call to a member function appendChild() on a non-object in /Applications/XAMPP/xamppfiles/htdocs/gen11/extensions/importcsv/content/content.index.php on line 29

Is Context actually available to you in the build function?

$this->Context->appendChild(new XMLElement('h2', __('Import / Export CSV')));

The above line seems to be causing the error! when I comment it out the page renders correctly

**Comment by nitriques** [comment]
Repo moved to: https://github.com/symphonists/importcsv
